import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export const generateDoctorReport = (username, disease, formData, result, history = []) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    let currentY = 20;

    // Helper: Add text and progress Y cursor
    const addText = (text, size, isBold, color = [0, 0, 0]) => {
        doc.setFont("helvetica", isBold ? "bold" : "normal");
        doc.setFontSize(size);
        doc.setTextColor(color[0], color[1], color[2]);
        const lines = doc.splitTextToSize(text, pageWidth - 40);
        doc.text(lines, 20, currentY);
        currentY += lines.length * (size * 0.4) + 2;
        if (currentY > 280) { doc.addPage(); currentY = 20; }
    };

    // 1. Header Section
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(15, 23, 42); // slate-900
    doc.text("Health Risk Assessment Report", pageWidth / 2, currentY, { align: "center" });
    currentY += 8;
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 116, 139); // slate-500
    doc.text(`Generated by NeuraHealth AI Diagnostics`, pageWidth / 2, currentY, { align: "center" });
    currentY += 5;
    const dateStr = new Date().toLocaleString();
    doc.text(`Report Date: ${dateStr}`, pageWidth / 2, currentY, { align: "center" });
    currentY += 15;

    // 2. Patient Information
    addText("Patient Details", 14, true, [59, 130, 246]); // blue-500
    currentY += 2;
    addText(`Name / Profile ID: ${username || "Anonymous User"}`, 11, false);
    
    const age = formData.age || "Not specified";
    const sex = formData.sex || (formData.gender || "Not specified");
    addText(`Demographic Context: Age ${age} | Gender: ${sex}`, 11, false);
    currentY += 8;

    // 3. Disease Information
    addText("Assessment Scope", 14, true, [59, 130, 246]);
    currentY += 2;
    addText(`Disease Target: ${disease.charAt(0).toUpperCase() + disease.slice(1)} Diagnostics`, 11, false);
    currentY += 8;

    // 5. Prediction Result
    addText("Predictive Risk Modeling Result", 14, true, [59, 130, 246]);
    currentY += 2;
    
    const { risk_percentage, risk_level, stroke_risk, care_plan } = result;
    const isHigh = risk_percentage > 70;
    addText(`Primary Risk Level: ${risk_level}`, 12, true, isHigh ? [239, 68, 68] : [34, 197, 94]);
    addText(`Quantitative Probability: ${risk_percentage}%`, 11, false);
    
    if (stroke_risk !== undefined) {
        currentY += 2;
        const strokeHigh = stroke_risk > 50;
        addText(`Secondary Screen (Near-Future Stroke): ${stroke_risk}%`, 11, true, strokeHigh ? [249, 115, 22] : [59, 130, 246]);
    }
    currentY += 8;

    // 4. Input Parameters (Table)
    addText("Clinical Biological Inputs", 14, true, [59, 130, 246]);
    currentY += 2;
    
    const tableData = Object.entries(formData)
        .filter(([key]) => key !== 'type' && key !== 'user_id')
        .map(([key, value]) => {
            const formattedKey = key.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
            return [formattedKey, String(value)];
        });

    autoTable(doc, {
        startY: currentY,
        head: [['Clinical Metric', 'Recorded Value']],
        body: tableData,
        theme: 'grid',
        headStyles: { fillColor: [51, 65, 85], textColor: 255 },
        styles: { fontSize: 10, cellPadding: 3 },
        columnStyles: { 0: { fontStyle: 'bold', cellWidth: 100 }, 1: { cellWidth: 70 } },
        margin: { left: 20, right: 20 },
    });
    
    currentY = doc.lastAutoTable.finalY + 10;
    if (currentY > 250) { doc.addPage(); currentY = 20; }

    // 8. Previous vs Current Comparison (If History Exists)
    if (history && history.length > 0) {
        // Find the most recent prediction for the SAME disease that isn't the current one
        // (Assuming history may or may not already have the current one appended. We filter by timestamp typically, 
        // but since we just clicked predict, the history might be the previous ones if we fetch before saving).
        // Let's just find the first history item that matches the disease. If it's literally identical in timestamp, skip it.
        const past = history.find(h => h.disease === disease);
        if (past && past.inputs) {
            addText("Longitudinal Comparison (Previous vs Current)", 14, true, [147, 51, 234]); // purple-600
            currentY += 2;
            
            const pastRisk = past.risk_percentage;
            addText(`• Overall Risk Trajectory: Changed from ${pastRisk}% to ${risk_percentage}%`, 10, false);
            
            let diffs = 0;
            // Iterate over current inputs and compare to past inputs
            for (const [key, currentVal] of Object.entries(formData)) {
                if (key !== 'type' && key !== 'user_id') {
                    const pastVal = past.inputs[key];
                    if (pastVal !== undefined && String(pastVal) !== String(currentVal)) {
                        diffs++;
                        const formattedKey = key.replace(/_/g, ' ');
                        addText(`• ${formattedKey} shifted from ${pastVal} → ${currentVal}`, 10, false);
                    }
                }
            }
            if (diffs === 0) {
                addText("• No changes automatically detected in explicit variable inputs since last run.", 10, false, [100, 116, 139]);
            }
            currentY += 8;
        }
    }

    if (currentY > 250) { doc.addPage(); currentY = 20; }

    // 6. Key Risk Factors & 7. Personalized Recommendations
    addText("Clinical AI Diagnostics & Care Protocol", 14, true, [59, 130, 246]);
    currentY += 2;

    if (care_plan) {
        addText(`AI Analysis Synthesis:`, 11, true);
        addText(care_plan.analysis || "Standard clinical baseline observed.", 10, false);
        currentY += 4;
        
        const recommendations = [
            { label: "Dietary Adjustments", text: care_plan.diet },
            { label: "Exercise Protocol", text: care_plan.exercise },
            { label: "Lifestyle Changes", text: care_plan.lifestyle },
            { label: "Medical Next Steps", text: care_plan.medical }
        ];

        recommendations.forEach(rec => {
            if (rec.text) {
                addText(`• ${rec.label}:`, 10, true);
                addText(`   ${rec.text}`, 10, false);
                currentY += 2;
                if (currentY > 270) { doc.addPage(); currentY = 20; }
            }
        });
    }

    // 9. Disclaimer Footer
    // Find bottom of page
    if (currentY > 260) { doc.addPage(); }
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    
    // Position 15 units from bottom
    const disclaimer = "DISCLAIMER: This report is generated using an AI-based system and is not a medical diagnosis. Please consult a certified healthcare professional for proper medical advice. The algorithmic risk scores are probabilistic and do not substitute clinical judgment.";
    const lines = doc.splitTextToSize(disclaimer, pageWidth - 40);
    doc.text(lines, 20, doc.internal.pageSize.getHeight() - 15);

    // Prompt download
    doc.save(`Health_Report_${username || "Anonymous"}_${disease}.pdf`);
};
